name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v2

      - name: Run `packer validate`
        id: validate
        run: "packer validate -syntax-only -var 'version=0.0.0' ./box-config.pkr.hcl"
        env:
          PACKER_LOG: 1
